# Generated by Django 5.0.1 on 2024-02-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0002_itemquantity_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
