# Generated by Django 5.0.1 on 2024-02-23 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0023_rename_phone_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
