# Generated by Django 5.0.1 on 2024-02-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0024_contactquantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Contact',
        ),
    ]
