# Generated by Django 5.0.1 on 2024-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0031_order_total_order_product_cost_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('nota de entrega', 'Nota de entrega'), ('factura', 'Factura')], max_length=16, null=True),
        ),
    ]
