# Generated by Django 5.0.1 on 2024-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0032_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('nota de entrega', 'Nota de entrega'), ('factura', 'Factura')], default=('factura', 'Factura'), max_length=16),
            preserve_default=False,
        ),
    ]
