# Generated by Django 5.0.1 on 2024-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0003_alter_product_item_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
