# Generated by Django 5.0.1 on 2024-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0004_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
