# Generated by Django 5.0.1 on 2024-02-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user_email',
        ),
    ]
