# Generated by Django 5.0.1 on 2024-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0009_rename_user_id_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
