# Generated by Django 5.0.1 on 2024-02-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0010_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('preparado', 'preparado'), ('pendiente', 'preparado')]),
        ),
    ]
