# Generated by Django 5.0.1 on 2024-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0014_alter_product_id_alter_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
