# Generated by Django 5.0.1 on 2024-02-16 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0019_user_is_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?58?\\d{14,15}$')]),
        ),
    ]
