# Generated by Django 5.0.1 on 2024-02-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0025_rename_client_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactQuantity',
        ),
        migrations.DeleteModel(
            name='ItemQuantity',
        ),
    ]
