# Generated by Django 5.0.1 on 2024-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0029_alter_order_client_id_alter_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
