# Generated by Django 4.2.10 on 2024-03-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0034_pricetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
