# Generated by Django 4.2.10 on 2024-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0035_pricetype_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricetype',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
