# Generated by Django 4.2.10 on 2024-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0036_order_pricetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
