# Generated by Django 4.2.10 on 2024-04-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0039_note_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
    ]
