# Generated by Django 4.2.10 on 2024-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0040_remove_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
