# Generated by Django 4.2.10 on 2024-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0041_alter_pricetype_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
