# Generated by Django 4.2.10 on 2024-05-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0042_remove_pricetype_percentage_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
