# Generated by Django 4.2.10 on 2024-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0043_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
