# Generated by Django 4.2.10 on 2024-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0045_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
