# Generated by Django 4.2.10 on 2024-06-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0046_receivable_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='client',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='seller',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
