# Generated by Django 4.2.10 on 2024-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0047_alter_receivable_client_alter_receivable_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='date',
            field=models.DateField(),
        ),
    ]
